### ISSUE TITLE
rename util.RsaDate2 and util.RsaDate3

### ISSUE THREAD

**Issue by zakird** [zmap/zlint#12]
Can we please rename these variables to be a bit more descriptive? I have _no_ idea what they are offhand.

**Comment by mhyder13** [comment]
RsaDate2 appears to be the day after 31 Dec 2010 (RsaDate). It looks like it was added as a constant by someone rather than adding 1 day at the place it was needed. RsaDate3 is one day after 31 Dec 2013, it appears to be off by one day for the same reason. Both dates are from the CA/B Baseline Requirements section 6.1.5.

**Comment by dadrian** [comment]
@mhyder13 Do you have a link to the BR's?
