### ISSUE TITLE
Add tld-update-bot as a collaborator

### ISSUE THREAD

**Issue by cpu** [zmap/zlint#258]
Hi folks :wave:

Following up on my comment in https://github.com/zmap/zlint/pull/255 I set up some quick automation for submitting gtld update PRs. I modelled it after the approach used by the [`publicsuffix-go`](https://github.com/weppos/publicsuffix-go) project's ["autopulls"](https://github.com/weppos/autopull/tree/autopull-publicsuffix-go) which were in turn based on a bash script by [nbio](https://github.com/nbio/autopull). The automation repository is here: https://github.com/cpu/zlint-autopull You can see an example automated PR here: https://github.com/cpu/zlint/pull/1

It uses Travis' cron build feature and a dedicated Github user (@tld-update-bot) to check once a day if there are `zlint-gtld-update` changes and if so creates a PR by pushing a branch to the zlint repo (named `autopull/master/<datestamp>`) and opening a PR with the generated diff against master. Someone will have to manually review & merge the PR at this point.

If this seems acceptable to the maintainers the only change that is required on your end is adding `tld-update-bot` as a collaborator so that branches can be pushed to this repo. If you haven't already you may also want to look into setting up [branch restrictions](https://help.github.com/articles/enabling-branch-restrictions/) on `master` to prevent any mishaps. Once `tld-update-bot` can push branches I'll change the automation from submitting PRs to my fork to this upstream project.

Thanks!

**Comment by zakird** [comment]
Thanks @cpu! This is great! I've added `tld-update-bot` as a collaborator. I think you may need to accept the invitation over email. 

Right now, master branch is less protected than I realized. Today, merging into master requires only 1+ reviews (from anyone I believe) and then any collaborator can merge. The SOP for other ZMap projects has been to restrict to a specific group of core contributors. This is often different between the various projects. I'd like to do the same here. There already exists a @zmap/zlint-maintainers team.

I'd like to add the currently unofficial core contributors: @dadrian, @kumarde, @titanous, @cpu, @robstradling, @zakird to @zmap/zlint-maintainers  and then restrict the master branch to that team. If folks have any objections, let me know. Otherwise I'll put that in place late tomorrow.

**Comment by cpu** [comment]
> I've added `tld-update-bot` as a collaborator. I think you may need to accept the invitation over email.

Done :ballot_box_with_check: :robot: 

I changed the Travis env vars to point to this repo. There should be a build every morning around this time going forward. I'll keep an eye on the logs until there is a change in the upstream TLD data.

> If folks have any objections, let me know. Otherwise I'll put that in place late tomorrow.

No objections from me. Thanks @zakird !
