### ISSUE TITLE
Certs with QcRetentionPeriod fails in new Zlint QCStatement validation

### ISSUE THREAD

**Issue by pazuzu2099** [zmap/zlint#272]
Hi, we have realized that all certificates with the QcRetentionPeriod are failing when they validate against Zlint. We could not find any certificate that work, nor among the sample certificates included in the application (we have not found any certificate with that field to check what is being verified).

The error is always the same 
ERROR: Checks that a QC Statement of the type id-etsi-qcs-QcRetentionPeriod has the correct form

Examples of three different CAs:

Government of Spain, Autoritat de Certificació de la Comunitat Valenciana (ACCV)
https://crt.sh/?id=1316564559&opt=zlint

Government of Spain, Fábrica Nacional de Moneda y Timbre (FNMT)
https://crt.sh/?id=1315542273&opt=zlint

Consorci Administració Oberta de Catalunya (Consorci AOC, CATCert)
https://crt.sh/?id=1305412472&opt=zlint

Is it a false positive? 
In the document ETSI EN 319 412-5 the syntax is

esi4-qcStatement-3 QC-STATEMENT ::= { SYNTAX QcEuRetentionPeriod IDENTIFIED
BY id-etsi-qcs-QcRetentionPeriod }

QcEuRetentionPeriod ::= INTEGER

id-etsi-qcs-QcRetentionPeriod OBJECT IDENTIFIER ::= { id-etsi-qcs 3 }

In crt.sh ASN1 tool, the field looks right 

SEQUENCE(2 elem)
	OBJECT IDENTIFIER0.4.0.1862.1.3
	INTEGER15

Is there an example of what zlint expects? 

Thanks
Regards, Jose Antonio

**Comment by zakird** [comment]
@mtgag would you be willing to take a quick look at this? I believe this is triggering some of the lints you recently introduced and I suspect you're more familiar with them than I am.

**Comment by mtgag** [comment]
Yes, we will take a look into it.

**Comment by rwbaumg** [comment]
I am seeing the same problem. 

This does appear to be a bug, since the ASN.1 encoding for retention period is correct in my test certificate according to ETSI documentation, and the extension is parsed just fine by a number of other tools.

The issue appears to be around [qc_stmt.go#L244)](https://github.com/zmap/zlint/blob/master/util/qc_stmt.go#L244) but I have not had a chance to do much debugging. The code appears fine at a glance, but since the error is wrapped and replaced by a static message I have no idea what the actual problem is.

In the meantime I'm pretty confident in saying this lint can be safely ignored in most cases.

**Comment by mtgag** [comment]
in the MTG fork a fix for this problem is provided. Please take a look at

https://github.com/zmap/zlint/pull/282

**Comment by zakird** [comment]
Given that this was resolved in #282, I'm going to close this.
