### ISSUE TITLE
Ambiguity on KeyUsage with ECC public key

### ISSUE THREAD

**Issue by jinNakamura** [zmap/zlint#291]
This issue was discussed in GoogleGroups and Bugzilla as follows:
<https://groups.google.com/forum/#!searchin/mozilla.dev.security.policy/ito%7Csort:date/mozilla.dev.security.policy/vDhKG7T6sCM/gKwMGqrYAwAJ>
<https://bugzilla.mozilla.org/show_bug.cgi?id=1560234>

If the KeyUsage of the certificate with ECC public key contains both digital signature and key encryption, cablint returns as the error when we run cablint.
However, current zlint does not return as the error.
If zlint can return as the error, I think zlint will be a better tool.

**Comment by cpu** [comment]
:wave: Thanks for opening an issue about this @jinNakamura. I spent a little bit of time reading the MDSP, LAMPS/SPASM, and Bugzilla discussion and I _think_ I'm up to speed now.

> If zlint can return as the error, I think zlint will be a better tool.

My understanding of the discussion consensus is that while this EKU/public key algorithm combination is non-sense it isn't clearly forbidden by the relevant RFCs/BRs as they are written today. Based on that conclusion there _could_ be an argument made that a lint for this condition should return a `Warn` level lint finding and not an `Error` level finding until the [RFC 5480 key usage clarification draft](https://datatracker.ietf.org/doc/draft-turner-5480-ku-clarifications/) is finalized.

Personally I'm not opposed to implementing a lint at the `Error` level (matching cablint) ahead of that clarification being finalized but I wanted to call this out specifically so that other zlint community members/relying users could weigh in.

**Comment by cardonator** [comment]
@cpu I agree with your assessment. Unfortunately, there are a number of places in the RFCs and BRs where the ambiguity of the term "MAY" is left up to the interpretation of the CABF and not clearly defined in the documentation. This was also the case with a previous PR that was rejected.

One of the difficult aspects of just flat out re-implementing cablint and x509lint functionality into zlint is that both of those linters have baked in "interpretation-level" errors and warnings. With the current ambiguity, I would argue that `Notice` level would be more appropriate, but I could be convinced toward `Warn` only because draft RFC 5480 could fix this ambiguity when finalized (at which point, `Error` would indeed make the most sense).

My main concern with making a resulting lint `Error` level right now would be that it sets an odd precedent for interpreting ambiguous rules that are only clearly defined in conversations that are easily lost to the winds of time after a few months on MDSP and Bugzilla. These platforms are great for discussion but there shouldn't be hidden compliance gremlins that can only be historically gleaned from those sources baked into zlint as opposed to the written rules codified in the RFCs and BRs.

**Comment by cpu** [comment]
@cardonator These are good points, thanks. You've convinced me that avoiding `Error` level for the time being is prudent since it would be easy to ratchet to that level in the future.

> With the current ambiguity, I would argue that Notice level would be more appropriate, but I could be convinced toward Warn only because draft RFC 5480 could fix this ambiguity when finalized (at which point, Error would indeed make the most sense).

I'm fairly fuzzy on what the distinction is meant to be between `Notice` and `Warn`, is there a reason you favour the one of the other in this case? 

One of my takeaway's from thinking about this issue is that it would be nice to capture some of this thought process into documentation somewhere. The docs for adding new lints in the README are fairly mechanical in nature and don't address the "spirit" of zlint or its lint result levels.

**Comment by cardonator** [comment]
@cpu based on our use case with zlint, we use Notices to log informational only lints during the issuance process, but they don't impact issuing the certs at all. When we get a Warning, the lint message has to be reviewed prior to issuance. When we get an Error, we alert and block issuance.

**Comment by zakird** [comment]
I haven't had a chance to look at this issue in depth, but I wanted to provide some historical context on the lint levels. We originally defined four levels with specific definitions. 

*Error:* Violation of RFC/BR `MAY` or `MAY NOT` type of statements. Certificate unequivocally does not conform to standard. Each lint _must_ have a specific statement like that in its citation.  

*Warn:* Violation of RFC/BR `SHOULD` or `SHOULD NOT` type statement. Again, there needs to be a specific citation, but it's not a misissuance based on this.
 
*Notice:* FYI types of statements or violations of non-codified community standards. We're much more lax about what goes here. These need to follow common sense, but do not need to be in the RFC or BR. In one case (presence of CN), we downgrade warn to notice.

*Fatal:* Something is wrong with the certificate such that we can't run the appropriate check.

**Comment by cardonator** [comment]
@zakird Thanks for the historical context. Out of curiosity, did you mean to say `MUST` and `MUST NOT` as part of the definition of an `Error` type? IMO much of the ambiguity comes from `MAY` and `MAY NOT` which don't necessarily imply that the opposite behavior is disallowed by the BRs/RFCs. This ambiguity was highlighted by Ryan in the referenced conversation:

> If I understand this question correctly, it's asking about whether the MAY
of values (X, Y, Z) means SHALL NOT/MUST NOT for values (A, B, C).
> 
> One interpretation says "You may set these values... or any other value".
The MAY tells clients what they should be prepared for, potentially
allowing them to reject any value outside of that if they're unprepared for
it.
> Another interpretation says "These are the ONLY values that MAY be present.
You MAY assert one or more of them, but you MUST NOT assert something else"
> 
>While I have thoughts on "what is sensible", I'm not sure if that's aligned
with "what is required"

**Comment by zakird** [comment]
🤦‍♂ You're absolutely correct. `MUST`/`MUST NOT` not `MAY`/`MAY NOT` May/May not would be warnings.

**Comment by jinNakamura** [comment]
Thank you for your comments.
As you said, the RFC has not been officially updated yet.
Therefore, we also thought that the Warn level is appropriate at this stage.
Also, if the RFC is officially updated, we will let you know the information again.

**Comment by cpu** [comment]
@zakird Thank you for the added historical context on the lint levels. That was really useful to read :+1:  I think your description of `Notice` matches up well with @cardonator's rationale/preference for this specific situation.

Unless someone else is more eager than me I'll work on banging out a quick lint for this at the `Notice` level in the next ~week.

> Also, if the RFC is officially updated, we will let you know the information again.

Thanks @jinNakamura, that would be great.

**Comment by cpu** [comment]
> Unless someone else is more eager than me I'll work on banging out a quick lint for this at the Notice level in the next ~week.

Here's a PR: https://github.com/zmap/zlint/pull/293 I'd appreciate :mag:'s and :eyes:'s when folks are free. Thanks!

**Comment by cpu** [comment]
Resolved in master by d9a29c3 :tada:

**Comment by dzacharo** [comment]
Updating the issue with the final RFC that clarifies Elliptic Curve Cryptography Subject Public Key Information and Key Usage bits.
- https://datatracker.ietf.org/doc/html/rfc8813
