### ISSUE TITLE
lints/result.go error: undefined strings.ReplaceAll

### ISSUE THREAD

**Issue by aysylu** [zmap/zlint#305]
I found this when running [Kritis](https://github.com/grafeas/kritis) integration tests, stack trace below:

```
Step 7/11 : RUN go get -u github.com/cloudflare/cfssl/cmd/...
 ---> Running in 1967f3c19ac9
# github.com/cloudflare/cfssl/vendor/github.com/zmap/zlint/lints
src/github.com/cloudflare/cfssl/vendor/github.com/zmap/zlint/lints/result.go:75:9: undefined: strings.ReplaceAll
The command '/bin/sh -c go get -u github.com/cloudflare/cfssl/cmd/...' returned a non-zero code: 2
```

**Comment by zakird** [comment]
Can you confirm the version of Go you're using? Offhand, I suspect you're using an outdated version, `strings.ReplaceAll` was added fairly recently.

**Comment by cardonator** [comment]
It was added in Go 1.12 so very likely out of date Go version on the Kritis side.

**Comment by cpu** [comment]
It's not made explicit in the readme but I consider `zlint` to require Go 1.12.x, largely because that's the only version used in [the project .travis.yml](https://github.com/zmap/zlint/blob/88c3f6b6f2f5ebc573c4679e548d6f1823d89213/.travis.yml#L5-L6) for running tests in CI. I'll open a PR to update the README to call this requirement out more explicitly.

I didn't intentionally introduce Go 1.12.x only functionality in https://github.com/zmap/zlint/commit/9971d62266e74547157ff95b5413227e21d8fe23 but I'm hesitant to go back and replace it with a more compatible `strings` function when the project doesn't test on Go 1.11.x. I recommend folks affected by this commit upgrade to Go 1.12. Sorry for the hassle @aysylu

**Comment by cpu** [comment]
> I'll open a PR to update the README to call this requirement out more explicitly.

https://github.com/zmap/zlint/pull/306

**Comment by aysylu** [comment]
@cpu @cardonator @zakird thank you all! I'll update Kritis infrastructure accordingly.
