### ISSUE TITLE
[Question] Regarding the way v2 is set up in the repo

### ISSUE THREAD

**Issue by cardonator** [zmap/zlint#408]
Hi all, is there a reason a literal v2 folder was created in concert with updating to v2 of the library? I believe the idiomatic way of handling this is to leave your repo alone and just add `/v2` to the end of the module line in the go.mod file. Post Go 1.12, go get seems to be capable of understanding this semantic without requiring changes to the representation of your library in the repo.

If my understanding of this is incorrect, please let me know.

**Comment by cpu** [comment]
:wave: Hi @cardonator, thanks for the question.

>  I believe the idiomatic way of handling this is to leave your repo alone and just add /v2 to the end of the module line in the go.mod file. Post Go 1.12, go get seems to be capable of understanding this semantic without requiring changes to the representation of your library in the repo.

What you're describing is what the Go module docs ["Releasing Modules (v2 or Higher)" section](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) calls the "Major Branch" approach: users import the code with the `v2` suffix but there's no matching directory in the source tree. In contrast, what ZLint has in master is what the docs call a "Major subdirectory" approach (though with no `v1` subdirectory because we only support v2 now).

I had originally opened a PR that would implement the "Major Branch" approach for ZLint (https://github.com/zmap/zlint/pull/393) but after discussing it more with @dadrian we decided the "Major subdirectory" approach was better. His PR to implement that has more context if you're interested: https://github.com/zmap/zlint/pull/398

Stuffing everything in a subdirectory is aesthetically unpleasant to me but I think it's nice to have import paths match the directory structure exactly (closer to Java packages) and it makes it easy to do concurrent development of a `v3`. 

Hope that helps explain the background!

**Comment by cardonator** [comment]
@cpu thanks for the explanation :+1:  That does make sense. I guess I skimmed over that section of the doc because I didn't like it (aesthetically ;) ).
