### ISSUE TITLE
Project Decision: What is a Warning?

### ISSUE THREAD

**Issue by zakird** [zmap/zlint#412]
When we initially started ZLint, all warnings and errors were expected to have a citation to an RFC or BRs statement. All other checks were expected to be Informational. There was a single exception to this rule: presence of subject CN since _every_ certificate has this. IIRC, some browsers would reject certificates without. Instead, all certificates today have an informational for this.

Since then, a few things have changed:

 * We've found that many things we want lints for are not explicitly forbidden by a standards document despite agreement among all contributors that no one should issue certificates in that manner. Some of these have snuck in as warnings (which bother me slightly since it violates our documentation). 

 * Many CAs block now issuance on a `WARNING` or `ERROR` but not an `INFO`. I'd guess everyone ignores `INFO`s. 

 * We have extended lint sources as new standards have emerged

With that in mind, I think we should make a project-level decision about what to do with citation-less-but-important lints. I think there are a few options:

 * Add a new lint source `COMMUNITY` and use the existing INFO/WARNING/ERROR levels there. If CAs want to exclude the ZLint community's best practices, that's their choice.

 * Change our definition of `WARNING` to not require a citation

 * Remove `CN` lint so that informational lints can be used in a blocking manner

I'm also of course open to others' ideas. What do folks think? 

/cc @cardonator, @sleevi, @cpu

**Comment by jsha** [comment]
> Remove CN lint so that informational lints can be used in a blocking manner

FWIW, the way Boulder currently uses zlint, via cloudflare/cfssl, allows setting both an error level and a set of ignored lints. So we are able to ignore the CN lint while treating all other informational lints as blocking.

**Comment by zakird** [comment]
Out of curiosity, do you block any others?

**Comment by sleevi** [comment]
@zakird Do you have a good example of a WARNING with an RFC citation? I'm assuming, perhaps incorrectly, that such a case would be when a SHOULD is violated, but perhaps there are stronger criteria?

**Comment by zakird** [comment]
I think that's correct, warnings are when a `SHOULD (NOT)` is violated. These RFB-based lints are warnings:

lint_distribution_point_missing_ldap_or_uri.go
lint_eku_critical_improperly.go
lint_ext_aia_access_location_missing.go
lint_ext_cert_policy_contains_noticeref.go
lint_ext_cert_policy_explicit_text_includes_control.go
lint_ext_cert_policy_explicit_text_not_nfc.go
lint_ext_cert_policy_explicit_text_not_utf8.go
lint_ext_crl_distribution_marked_critical.go
lint_ext_ian_critical.go
lint_ext_key_usage_not_critical.go
lint_ext_policy_map_not_critical.go
lint_ext_policy_map_not_in_cert_policy.go
lint_ext_subject_key_identifier_missing_sub_cert.go
lint_name_constraint_on_edi_party_name.go
lint_name_constraint_on_registered_id.go
lint_name_constraint_on_x400.go

For example in `lint_ext_aia_access_location_missing`, 
```func init() {
	lint.RegisterLint(&lint.Lint{
		Name:          "w_ext_aia_access_location_missing",
		Description:   "When the id-ad-caIssuers accessMethod is used, at least one instance SHOULD specify an accessLocation that is an HTTP or LDAP URI",
		Citation:      "RFC 5280: 4.2.2.1",
		Source:        lint.RFC5280,
		EffectiveDate: util.RFC5280Date,
		Lint:          &aiaNoHTTPorLDAP{},
	})
}```

**Comment by cardonator** [comment]
Thanks for spinning this conversation up, @zakird . My initial gut reaction to your proposal is that we allow Warning lints to be created whose citation references industry best practices that aren't codified in a requirements document in any manner but are recommended to follow. This could be accomplished either by creating community lints (which I know was a controversial topic during the recent v2 refactor), or by having a citation type of something like BestPractice with a description of where that best practice originates from (possibly a Ryan email? 😇)

For reference, we currently alert on Warnings but don't block issuance due to them. For our purposes, it would be unfortunate to have any Warning level lint that was indicative of a misissuance. We log our lint responses for later review and have a process by which we ensure that any ignored Info or Warning level lints are not suggestive of issuance problems.

This was more for informational purposes

**Comment by sleevi** [comment]
Thanks for confirming, @zakird. That totally makes sense to me and is a clear and unambiguous requirement. I'm wholly supportive of continuing to require that level for warnings.

I worry that both community lints/best practices/INFO will inherently be subjective. Even when I totally agree with them / want the desired behaviour, my concern is that CAs would disagree, and thus end up disabling such lints, leaving added work for the ZLint maintainers to support code that they aren't sure is being used in practice.

I also worry there would be two standards for community lints - those that are ambiguous and unstated, but "everyone" "knows" the "right" answer, and those that do represent good practices. The latter seem like they'll necessarily be controversial (for example, a lint about certificate lifetimes...), while the former seem less controversial. If the former is all we care about, should there be a burden to have filed a spec issue in the appropriate spec? That way, if anyone disagrees with a given lint, they can join the relevant SDO to adjudicate the expectation/meaning, rather than leaving it to the ZLint community to arbitrate?

**Comment by zakird** [comment]
I agree with keeping definition of `WARNING` and `ERROR` simple/straight-forward, especially for anything in the RFC/CAB sources. I also agree that some best practices will be subjective and in general, I think that we should stick away from very subjective things. I have no interest wadding into a certificate length controversy. 

That said, I'm not convinced that all best practices are controversial, and standards can take time to change. The well-formed IPv6 address lint sticks in my mind as I write this. If CAs want to contribute lints for something like that, there's not much discussion, I'm happy to have these as long as they're segmented (i.e., have community source). If CXAs don't want them, they're fine to exclude them. The API provides this functionality. Or, they can participate in the discussion in the future. It's an open community.

**Comment by cardonator** [comment]
Aren't there already a number of (helpful) lints like that in the AWSLabs source? I think that does indicate that, for at least some CAs or people, best practice type of lints can be helpful in a variety of ways.

**Comment by cpu** [comment]
I don't have strong feelings here. Happy to follow consensus.
