### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by cardonator** [zmap/zlint#465]
Is there any way we can cut a patch release for zlint? As the 397 day cert validity requirement has gone into place today, the recent changes merged to ignore that check on certificates marked as CAs would be helpful to prevent throwing errors on the lint for that requirement.

Thanks!

**Comment by cpu** [comment]
> Is there any way we can cut a patch release for zlint? 

Sure! I can work on cutting one later this evening. There are new lints in the [diff from v2.1.0](https://github.com/zmap/zlint/compare/v2.1.0...master) so per the [README versioning info](https://github.com/zmap/zlint#versioning-and-releases) it'll be a MINOR release to v2.2.0 instead of a patch release.

**Comment by cardonator** [comment]
Thanks!

**Comment by cpu** [comment]
[v2.2.0-rc1](https://github.com/zmap/zlint/releases/tag/v2.2.0-rc1) is available now. Please report any trouble on the [call for testing issue](https://github.com/zmap/zlint/issues/466). I've also posted to the [announcements mailing list](https://groups.google.com/forum/#!topic/zlint-announcements/Cj314eYNhBc). I'll cut the final tag next week if everything goes well.

Thanks for the prompt @cardonator !
