### ISSUE TITLE
[Discussion] Lints that cover both SHOULD and MUST conditions in the same lint

### ISSUE THREAD

**Issue by cardonator** [zmap/zlint#476]
Hi all, I wanted to discuss the precedent set by some recent lints in terms of combining SHOULD and MUST conditions into one lint. 

In earlier zlint times, every lint was clearly discernible by its name as to whether it would return an Error, Warn, or Notice condition (by the `e_` prefix, for example). That meant you could use the lint name to distinguish zlint related conditions in your logs pretty easily as often the name of the lint also described what condition you were running into.

Recently we've added some lints that cover multiple SHOULD and MUST conditions and could return Notice, Warning, and Error conditions inside the same lint. A recent example is `e_tls_server_cert_valid_time_longer_than_398_days` which return a warning for SHOULD between 397-398 day validity. Due to this, the lint name became less readable as to what condition it was failing to meet and getting a warning on.

So I thought I would raise this conversation about what the project _should_ be doing in these cases. Should we have multiple lints for covering the various possible conditions in the industry requirements? Does it make sense for an `e_` lint to also return other types of conditions? If so, should we adjust how we look at Lint naming to ensure it aligns more appropriately with the conditions the lint is checking? (As a poor man's example, maybe something like `m_tls_server_cert_validity` perhaps `m_` for multiple potential response statuses?)

**Comment by robstradling** [comment]
Thanks for starting this discussion, @cardonator.  I'm interested in the outcome because https://crt.sh/?zlint=issues currently shows a misleading "TLS server certificates issued on or after September 1, 2020 00:00 GMT/UTC must not have a validity period greater than 398 days" warning for certs with validity periods greater than 397 days but not greater than 398 days.

I would prefer to see SHOULD and MUST conditions in separate lints.  e.g., in this particular case, move the "SHOULD...397 days" condition into a separate lint named `w_tls_server_cert_valid_time_longer_than_397_days`.

**Comment by zakird** [comment]
This sounds like a regression and we need to fix it. Lints should only return a warning or error based on their type.

**Comment by zakird** [comment]
This is not explicitly laid out in https://github.com/zmap/zlint/blob/master/CONTRIBUTING.md, but we should update to match.
