### ISSUE TITLE
Stale PSL data

### ISSUE THREAD

**Issue by robstradling** [zmap/zlint#523]
https://crt.sh/?id=3767009644&opt=zlint currently triggers `n_san_iana_pub_suffix_empty`, even though `dominic.ua` was removed from the PSL just over 6 months ago (https://github.com/publicsuffix/list/commit/ac45e5ab644d704f4ec392a2271ad3454bcc6378).  This seems to be because publicsuffix-go hasn't had a stable release since 16th February 2020 (v0.13.0, see https://github.com/weppos/publicsuffix-go/releases).

Since publicsuffix-go is regularly autopulling PSL updates (see https://github.com/weppos/publicsuffix-go/commits/master/publicsuffix/rules.go), would it make sense to change ZLint's (and ZCrypto's) `go.mod` to use the latest unstable version of publicsuffix-go instead of the latest stable version?

**Comment by cpu** [comment]
> would it make sense to change ZLint's (and ZCrypto's) go.mod to use the latest unstable version of publicsuffix-go instead of the latest stable version?

Definitely. We should do this + automate opening PRs with the version bumps. Thanks for flagging.

**Comment by robstradling** [comment]
On a related note...
I see that ZLint's gtld_map.go records the delegation date and (if relevant) removal date of each GTLD.  I haven't checked but I presume that the GTLD-related lints consider whether or not a certificate's notBefore date is within that time period.  (i.e., if the GTLD existed when a cert was issued, the CA did not misissue).
In contrast, it looks like publicsuffix-go only provides a point-in-time view of the PSL.  Do we need ZLint/ZCrypto to keep track of the PSL's history, by recording the dates when each PSL entry was added and (if relevant) removed?  Or would that be overkill?

**Comment by cpu** [comment]
> I haven't checked but I presume that the GTLD-related lints consider whether or not a certificate's notBefore date is within that time period. (i.e., if the GTLD existed when a cert was issued, the CA did not misissue).

The [`e_dnsname_not_valid_tld` lint](https://github.com/zmap/zlint/blob/master/v3/lints/cabf_br/lint_dnsname_right_label_valid_tld.go) does, yes. It uses [`util.HasValidTLD`](https://github.com/zmap/zlint/blob/d8314a3cab4a3b971016681608f217b9a2655126/v3/util/gtld.go#L73-L90) with the cert's `NotBefore` for this.

>  would it make sense to change ZLint's (and ZCrypto's) go.mod to use the latest unstable version of publicsuffix-go instead of the latest stable version?

As far as I can tell the only place that directly touches the PSL in this repo is the (fairly pointless looking) helper function [`ICANNPublicSuffixParse`](https://github.com/zmap/zlint/blob/d8314a3cab4a3b971016681608f217b9a2655126/v3/util/fqdn.go#L113-L115) in `util/fqdn.go` and it has **zero** references across the codebase so I think we can probably drop the direct `publicsuffix-go` dependency in ZLint and at least remove one thing from the equation (impl'd in https://github.com/zmap/zlint/pull/525)

Everywhere else uses `ZCrypto`'s [`x509.Certificate.GetParsedDNSNames` function](https://github.com/zmap/zcrypto/blob/e54a5822fb7e7fa744aaa352738b3a77f7472c2b/x509/x509.go#L848-L869).

> In contrast, it looks like publicsuffix-go only provides a point-in-time view of the PSL. Do we need ZLint/ZCrypto to keep track of the PSL's history, by recording the dates when each PSL entry was added and (if relevant) removed? Or would that be overkill?

I think that probably makes some sense but I'm not sure it's the best place to direct resources relative to the payoff. 

Somewhat relatedly, it might make sense to consider using a ZMap fork of publicsuffix-go so that we could add features like this. I'm maintaining the automation that updates `publicsuffix/list` w/ gTLD data, and the automation that updates ZLint's gTLD data. We're leaning on a 3rd party for keeping the automation on `weppos/publicsuffix-go` flowing (and there is an umerged PR backup presently). Probably it would expedite things and make everyone's lives easier if we helped with that part more directly as well :man_shrugging:

**Comment by cpu** [comment]
> would it make sense to change ZLint's (and ZCrypto's) go.mod to use the latest unstable version of publicsuffix-go instead of the latest stable version?

Working on ZCrypto automation to track master: https://github.com/zmap/zcrypto/pull/240

We'll still have to figure out the ZLint side when ZCrypto updates. We could continue to chain github actions and make a bot PR here for each ZCrypto update.

**Comment by cpu** [comment]
ZCrypto and ZLint master are both using the latest available publicsuffix-go data. ZCrypto should get PRs automatically when there are new updates. I'll keep an eye on it and match with ZLint manually for now to see how the new process goes.
