### ISSUE TITLE
How to check for lints from JSON data got from the CT logs?

### ISSUE THREAD

**Issue by 1209973** [zmap/zlint#573]
Dear maintainers!

Do you have a way to run zlint to check for lint issues when the JSON data from a CT log is given as the input?

Currently, most of the functions required the input to be in the x509.Certificate type.  And if there isn't any way to run Zlint with JSON input, Is there is any way to convert the JSON data into an x509.Certificate type?

**Comment by christopher-henderson** [comment]
Howdy @1209973! As of today, ZLint operates on a single certificate in isolation (that is, one at a time). If you would like to lint each certificate within your CT logs I think I would suggest that you write a wrapper script that can extract each individual certificate that you're interested in and run ZLint from there.

So something like...

```python
for log in ctlogs:
    zlint(log['certificate'])
```

**Comment by dadrian** [comment]
You can also use [ZCertificate](https://github.com/zmap/zcertificate) to run ZLint against PEMs extracted from a CT log using some other tool.

**Comment by 1209973** [comment]
> Howdy @1209973! As of today, ZLint operates on a single certificate in isolation (that is, one at a time). If you would like to lint each certificate within your CT logs I think I would suggest that you write a wrapper script that can extract each individual certificate that you're interested in and run ZLint from there.
> 
> So something like...
> 
> ```python
> for log in ctlogs:
>     zlint(log['certificate'])
> ```

@christopher-henderson, So in this example code, log[çertificate'] is of type PEM or a JSON or x509.Certificate. Because when we use [Certstream](https://github.com/CaliDog/certstream-python) to capture CT log data we get a JSON output in which the data field would contain all the properties of the certificate in JSON format. Is it possible to use that JSON format in Zlint?

``` json
{
    "message_type": "certificate_update",
    "data": {
        "update_type": "X509LogEntry",
        "leaf_cert": {
            "subject": {
                "aggregated": "/CN=app.theaffairsite.com",
                "C": null,
                "ST": null,
                "L": null,
                "O": null,
                "OU": null,
                "CN": "app.theaffairsite.com"
            },
```

**Comment by christopher-henderson** [comment]
ooooof x509 serialized as JSON rather than as ASN1 is indeed outside of the scope of this tool. We support PEM, DER, and base64 encoded certificates (anything that is itself just a re-encoding or armoring of ASN1). This is especially tricky because there are a non trivial number of lints that take into consideration precisely the ASN1 serialization of the given certificate.

Unless I missed something about how ZCertificate might pull this off @dadrian ?

@cpu can you think of any recourse here (they're getting their certificates as a JSON objects rather than ASN1 and still want to lint it)?

**Comment by cpu** [comment]
> @cpu can you think of any recourse here (they're getting their certificates as a JSON objects rather than ASN1 and still want to lint it)?

No, I can't. This seems like a limitation the OP should pursue with Certstream. The certificate transparency logs _do_ contain the DER encoded leaf certificates in a form that would be easily lintable but it looks to me like Cerstream creates a friendly JSON representation without exposing the original underlying certificate. I would recommend making a feature request with Certstream or consuming the certificate transparency logs directly instead of with an intermediate service like Certstream.

**Comment by dadrian** [comment]
It is not possible to lint a JSON representation (even the ZCrypto one), since they drop necessary encoding information about the ASN.1 itself. You can only lint a DER-encoded certificate.
