### ISSUE TITLE
Cutting zlint 3.6.0

### ISSUE THREAD

**Issue by robplee** [zmap/zlint#776]
By my count, there've been over 30 PRs merged including quite a number of new lints since we last cut a release so should we make zlint 3.6.0?

I've tested a zlint integration with importing the latest changes and don't see any issues necessitating a major release. Particular as #775 was scoped to checking new zlint code rather than existing code that may exist around zlint as it is imported.
 
I feel that after #775 and #767, the logical next step is to remove the deprecated interfaces but that'll definitely have to be called 4.0.0.  Therefore, I suggest we cut a minor release now to get the new lints around SMIME and CRLs out into the wild and then 4.0.0 can be about removing LintInterface and we can try to keep release notes for that short.

**Comment by zakird** [comment]
Makes sense to me! In general, I'd love to get in the habit of doing smaller point releases more often.

**Comment by cardonator** [comment]
Agreed, was going to comment the same thing today and forgot. Regarding 4.0.0 release, should we wait a bit until the SMIME lints are more robust before making another major bump? I know we are anxious for more SMIME but will need to do some refactoring of other code when we do remove the old interfaces.

**Comment by christopher-henderson** [comment]
I was literally thinking on this the other day. To several points...

#### Minor Bump, not Major
I agree that now is a good time to do a minor bump. I reckon that we will eserve the major for when we have 

1. Completed deleted the the `Lint` interface 
2. Taken inventory on other items that are on peoples' wishlist  that would necessitate a major release (just so that we get everything in one go).

#### SMIME
Releasing the extant lints in a minor release is a good canary in the coal mine, I think. It's tempting to wait for a release to have more of them, however I admit that I don't see anything inherently wrong with trickling them out.

Given no objections, I can certainly cut a release before the holiday storm is upon us.

**Comment by christopher-henderson** [comment]
Release candidate up at https://github.com/zmap/zlint/releases/tag/v3.6.0-rc1

**Comment by christopher-henderson** [comment]
Cut in https://github.com/zmap/zlint/releases/tag/v3.6.0 :tada:
